### ISSUE TITLE
composer.json update for typo3 11.5

### ISSUE THREAD

**Issue by Cameros-agency** [ameos/ameos_dailymotion#3]
Hi !

Thank you for your extension !

Could you update the composer.json to be compatible with version ^11.5 please ?
Since typo3 isn't in version / branch dev-master, installation fails :/

Thank you in advance

**Comment by ameos** [comment]
Hi,

It's done.

Regards
Stéphane

**Comment by Cameros-agency** [comment]
Thank you for your quick change :)
